const express = require('express')
const userRouter = require("./routes/user")
const productRouter = require('./routes/product')
const addressRouter = require("./routes/address")
const cartRouter = require("./routes/cart")
const communityRouter = require("./routes/community")
const helpRouter = require("./routes/help")
const orderRouter = require("./routes/order")
const bodyParser = require("body-parser")
const app = express()
app.listen(8080)
app.use(express.static('./public'))
app.use(bodyParser.urlencoded({
  extended:false
}))
app.use(bodyParser.json())
app.use('/user',userRouter)
app.use('/product',productRouter)
app.use('/address',addressRouter)
app.use('/cart',cartRouter)
app.use('/community',communityRouter)
app.use('/help',helpRouter)
app.use('/order',orderRouter)
